### ISSUE TITLE
youtube скачивание умерло

### ISSUE THREAD

**Issue by Dimoon12** [Dimoon12/Matrix_malafit_bot#3]
Очень странная ошибка, по какой то причине бот не хочет получать информацию о длине видео
```
Traceback (most recent call last):
  File "[Patch to home]matrix/main.py", line 199, in <module>
    bot.run()
  File "[Patch to home].local/lib/python3.10/site-packages/simplematrixbotlib/bot.py", line 88, in run
    asyncio.run(self.main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "[Patch to home].local/lib/python3.10/site-packages/simplematrixbotlib/bot.py", line 81, in main
    await self.async_client.sync_forever(timeout=3000, full_state=True)
  File "[Patch to home].local/lib/python3.10/site-packages/nio/client/async_client.py", line 1199, in sync_forever
    await self.run_response_callbacks([await response])
  File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "[Patch to home].local/lib/python3.10/site-packages/nio/client/async_client.py", line 1046, in sync
    response = await self._send(
  File "[Patch to home].local/lib/python3.10/site-packages/nio/client/async_client.py", line 792, in _send
    await self.receive_response(resp)
  File "[Patch to home].local/lib/python3.10/site-packages/nio/client/async_client.py", line 704, in receive_response
    await self._handle_sync(response)
  File "[Patch to home].local/lib/python3.10/site-packages/nio/client/async_client.py", line 671, in _handle_sync
    await self._handle_joined_rooms(response)
  File "[Patch to home].local/lib/python3.10/site-packages/nio/client/async_client.py", line 598, in _handle_joined_rooms
    await asyncio.coroutine(cb.func)(room, event)
  File "[Patch to home]matrix/main.py", line 70, in echo
    if video.length > 3600:
  File "[Patch to home].local/lib/python3.10/site-packages/pytube/__main__.py", line 383, in length
    return int(self.vid_info.get('videoDetails', {}).get('lengthSeconds'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f44beec7d90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f44beede380>, 91745.034709063)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f44beec7dc0>

```

**Comment by Dimoon12** [comment]
???
pytube.exceptions.VideoUnavailable: [Видео] is unavailable
Просто WHY? рандомное видео из открытого доступа
Не понятно откуда эта ошибка, реакция такая от всех видео

**Comment by Dimoon12** [comment]
Виной всему .lowercase() который в начале программы делал все буквы коротышкинскими, в том числе и из ссылки
